name: Generate pacman animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1️⃣ Clonar repo (opcional, pero recomendado)
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Generar SVG
      - name: Generate pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # 3️⃣ Mover SVG a dist (opcional)
      - name: Create dist folder
        run: mkdir -p dist

      - name: Move SVG to dist
        run: mv pacman-contribution-graph.svg dist/

      # 4️⃣ Subir a la rama output
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
